"""room number from guests removed

Revision ID: 27f75ac8bfd8
Revises: 02f8baf461bc
Create Date: 2026-01-06 20:46:08.946961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f75ac8bfd8'
down_revision: Union[str, Sequence[str], None] = '02f8baf461bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_column('room_number')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_number', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
