"""initial migration

Revision ID: 5a7de4f1355d
Revises: 
Create Date: 2026-01-06 11:30:00.458427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7de4f1355d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('daily_price', sa.Float(), nullable=False),
    sa.Column('room_type', sa.Enum('SINGLE', 'DOUBLE', 'SUIT', name='roomtype'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'DIRTY', name='roomstatus'), server_default=sa.text("'avaliable'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    # ### end Alembic commands ###
