"""create rooms table

Revision ID: 895599f15939
Revises: 843a74607adb
Create Date: 2026-01-05 19:11:17.885058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895599f15939'
down_revision: Union[str, Sequence[str], None] = '843a74607adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('daily_value', sa.Float(), nullable=False),
    sa.Column('room_type', sa.Enum('single', 'double', 'suit', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('avaliable', 'unavailable', 'maintenance', native_enum=False), server_default=sa.text("'avaliable'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    # ### end Alembic commands ###
